services:
  - type: web
    name: flask-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    branch: main
    region: frankfurt
    autoDeploy: true

cronJobs:
  - name: refresh-parquet-data
    schedule: "0 */6 * * *"  # every 6 hours
    command: ./download_data.sh