name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Redeploy on Merge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ vars.HETZNER_HOST }}
            username: ${{ vars.HETZNER_USER }}
            key: ${{ secrets.HETZNER_SSH_KEY }}
            script: |
              sudo apt-get update -y
              sudo apt-get install -y git
              sudo apt-get install python3-venv -y
  
              if [ ! -d "$HOME/app" ]; then
                  git clone https://github.com/Statophobia/BahnIQ.git ~/app
              fi
  
              cd ~/app
              git fetch origin
              git reset --hard origin/main
              echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
              chmod +x start.sh
              ./start.sh