name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    # Replace the below with pytest
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ vars.HETZNER_HOST }}
            username: ${{ vars.HETZNER_USER }}
            key: ${{ secrets.HETZNER_SSH_KEY }}
            script: |
              sudo apt-get update -y
              sudo apt-get install -y git
              sudo apt install -y python3 python3-pip
  
              if [ ! -d "$HOME/app" ]; then
                  git clone https://github.com/Statophobia/BahnIQ.git ~/app
              fi
  
              cd ~/app
              git pull origin main
              pip3 install -r requirements.txt
              chmod +x start.sh
              ./start.sh