name: Refresh Data

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
    - name: Refresh via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ vars.HETZNER_HOST }}
        username: ${{ vars.HETZNER_USER }}
        key: ${{ secrets.HETZNER_SSH_KEY }}
        script: |
          cd ~/bahniq
          git fetch origin
          git reset --hard origin/main
          chmod +x refresh_data.sh
          ./refresh_data.sh >> refresh_data.log 2>&1